### PR TITLE
clean up

### PR DESCRIPTION
**Pull request by yaelmoshi**
I noticed a lot of EAPI errors in portage, because of EAPI version 5, so I did a little cleanup and also deleted ancient versions.

### CODE REVIEW

**Review by orumin — CHANGES_REQUESTED** [review]
file permission shouldn't be changed unnecessarily

**Comment by orumin** [comment]
@sm-moshi could you revert change of file permission?
if you done it, i will merge.

**Comment by isityael** [comment]
I'm actually a total noob when it comes to git. How do I change the permission?

**Comment by orumin** [comment]
@sm-moshi you can use `git config core.filemode false`

**Comment by orumin** [comment]
this option effects future commit only.
you should create new commit for revert change of file permission

**Comment by isityael** [comment]
will do.

**Pull request closed without merging**
